telegram:
  token: bot1346021515:AAGE66ZdbYj_SilFF9jHoKB8MFY_LkIDAgs
  chatId: -407867414
  baseUrl: https://api.telegram.org

binance:
  futureUrl: https://dapi.binance.com/dapi/v1
  spotUrl: https://api.binance.com/api/v3

server:
  port: 8080